version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    container_name: shoppingcartDB
    ports:
    - "5432:5432"
  back:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --workers=2 --threads=2 shopping_cart.wsgi -b 0.0.0.0:8000 --log-file=-
    container_name: shoppingcartBackend
    volumes:
      - .:/code
    ports:
    - "8000:8000"
